services:

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: chat_open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  redis:
    container_name: chat_redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: chat_searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8084:8080"
    volumes: # for use with portainer
      # - /mnt/portainer-compose-unpacker/stacks/chat/chat/searxng:/etc/searxng:rw
      # - /mnt/portainer-compose-unpacker/stacks/chat/chat/searxng/settings.yml:/etc/searxng/settings.yml:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
  tika:
    container_name: chat_tika
    image: apache/tika:2.9.2.1-full
    ports:
      - "9998:9998"
    restart: unless-stopped

volumes:
  open-webui: {}
  valkey-data2: {}
